---
- name: install some packages
  hosts: all
  tasks:
    - name: install sw packages
      apt:
        name: "{{item.a}}" 
        state: "{{item.b}}"
        udate_cache: "{{item.c}}"
      with_items:
    - {a: tree, b: present, c: yes}
    - {a: git, b: absent, c: yes}
    - {a: maven, b: present, c: yes}
    - {a: default-jdk, b: absent, c: yes}


...
