---
- name: create a user if not present update the user's password
  hosts: all
  tasks:
    - name: create a user
      user:
        name: abdul
      register: result
    - name: print the output
      debug: 
        var: result
    - name: update the password
      user:
        name: abdul
        password: 123456
      when:
          result.changed==true
